import { chromium } from '@playwright/test';
import { startServer } from './server.ts';
Deno.test({name:'built sidebar and DeepSeek: all transports, background reattachment, result routing and replay',sanitizeOps:false,sanitizeResources:false,fn:async()=>{
 // The fixture declares this browser-global recorder; it is never present on live DeepSeek.
 const fixture=startServer();
 const executablePath = Deno.env.get('MCP_TEST_BROWSER');
 console.log('Browser executable:', executablePath ?? 'Playwright Chromium');
 const context=await chromium.launchPersistentContext('',{headless:false,...(executablePath ? {executablePath} : {channel:'chromium'}),args:[`--disable-extensions-except=${Deno.cwd()}/.output/chrome-mv3`,`--load-extension=${Deno.cwd()}/.output/chrome-mv3`]});
 try{
  const worker=context.serviceWorkers()[0]??await context.waitForEvent('serviceworker');const id=new URL(worker.url()).host;
  let panel=await context.newPage();await panel.goto(`chrome-extension://${id}/sidepanel.html`);
  await panel.getByText('0 connected',{exact:true}).waitFor();
  await panel.click('#new-profile');await panel.locator('[name="name"]').fill('unsaved draft');
  await panel.click('#tab-settings');await panel.locator('#tab-settings').press('Home');
  if(await panel.locator('[name="name"]').inputValue()!=='unsaved draft')throw new Error('Tab switch lost profile draft');
  await panel.click('#cancel-profile');
  for(const transport of ['http','sse','ws']){
   await panel.click('#new-profile');await panel.locator('[name="name"]').fill(transport);
   await panel.locator('[name="url"]').fill(transport==='ws'?fixture.url.replace('http:','ws:')+'/ws':fixture.url+'/'+(transport==='sse'?'sse':'mcp'));
   await panel.locator('[name="transport"]').selectOption(transport);await panel.getByRole('button',{name:'Save profile',exact:true}).click();
   await panel.locator('#profile-form').waitFor({state:'hidden'});
   const profile=panel.locator('.profile-card').filter({hasText:transport==='ws'?'ws://':fixture.url+'/'+(transport==='sse'?'sse':'mcp')});
   await panel.bringToFront();
   await profile.getByRole('button',{name:'Connect',exact:true}).click();await profile.getByText('connected',{exact:true}).waitFor();
   await panel.click('#tab-tools');
   const tool=panel.locator('.tool-card').filter({has:panel.locator('.tag').getByText(transport,{exact:true})});
   await tool.locator('summary').first().click();await tool.getByLabel('Read-only',{exact:true}).check();await tool.getByRole('button',{name:'Save review'}).click();
   await tool.getByLabel('echo JSON arguments').fill(JSON.stringify({value:'sidebar-'+transport}));
   await panel.click('#tab-settings');await panel.locator('#tab-settings').press('ArrowLeft');
   await panel.locator('#tab-activity').press('ArrowLeft');
   if(await tool.getByLabel('echo JSON arguments').inputValue()!==JSON.stringify({value:'sidebar-'+transport}))throw new Error('Tab switch lost tool arguments');
   await tool.getByRole('button',{name:'Run tool'}).click();await panel.click('#tab-activity');await panel.locator('#results').getByText(new RegExp('sidebar-'+transport)).waitFor();
   await panel.click('#tab-servers');
  }
  await panel.close();panel=await context.newPage();await panel.goto(`chrome-extension://${id}/sidepanel.html`);await panel.getByText('3 connected',{exact:true}).waitFor();
  await worker.evaluate(async()=>{const extension=globalThis as unknown as {chrome:{offscreen:{closeDocument():Promise<void>}}};await extension.chrome.offscreen.closeDocument();});
  await panel.reload();await panel.getByText('3 connected',{exact:true}).waitFor();
  await panel.click('#tab-settings');
  const preview=panel.locator('#system-prompt');await panel.getByText('Preview instructions and available tools',{exact:true}).click();
  await preview.getByText(/Available tools from currently connected servers/).waitFor();
  await panel.locator('#copy-system-prompt').click();await panel.getByText('Copied',{exact:true}).waitFor();
  await panel.locator('#system-prompt-title').scrollIntoViewIfNeeded();await panel.screenshot({path:'.output/system-prompt-proof.png'});
  // Chrome dismisses permission prompts from unfocused windows; retry with
  // the panel in front until the site-access grant lands.
  let accessGranted=false;
  for(let attempt=0;attempt<6&&!accessGranted;attempt++){
   await panel.bringToFront();
   await panel.getByRole('button',{name:'Enable DeepSeek access'}).click();
   try{await panel.getByText('Access granted',{exact:true}).waitFor({timeout:5000});accessGranted=true;}
   catch{await panel.waitForTimeout(1000);}
  }
  if(!accessGranted)throw new Error('DeepSeek site access was not granted (click Allow on the permission prompt)');
  await context.route('https://chat.deepseek.com/**',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><body><main id="messages"></main><textarea placeholder="Message DeepSeek"></textarea><div role="button" class="ds-button--circle ds-button--primary ds-button--disabled"><svg><path d="M8.3125 0.980206"></path></svg></div><script>window.sent=[];const input=document.querySelector('textarea'),send=document.querySelector('[role=button]');input.addEventListener('input',()=>send.classList.toggle('ds-button--disabled',!input.value));send.addEventListener('click',()=>{window.sent.push(input.value);input.value='';send.classList.add('ds-button--disabled');});</script></body></html>`}));
  const firstChat=await context.newPage();await firstChat.goto('https://chat.deepseek.com/');
  await firstChat.locator('textarea').fill('Inspect my workspace');await firstChat.locator('textarea').press('Enter');
  await firstChat.waitForFunction(()=> 'sent' in window && Array.isArray(window.sent) && window.sent.length===1);
  const firstSent=await firstChat.evaluate(()=> (window as unknown as {sent:string[]}).sent[0]);
  if(!firstSent.endsWith('User request:\nInspect my workspace'))throw new Error('First user request not preserved');
  const listed=JSON.parse(firstSent.split('Available tools from currently connected servers:\n')[1].split('\n\nUser request:')[0]);
  if(JSON.stringify(listed.map((tool:{server:string})=>tool.server).sort())!==JSON.stringify(['http','sse','ws']))throw new Error('Missing connected tool listings');
  await firstChat.locator('textarea').fill('Follow up');await firstChat.locator('[role="button"]').click();
  await firstChat.waitForFunction(()=> 'sent' in window && Array.isArray(window.sent) && window.sent.length===2);
  if(await firstChat.evaluate(()=> (window as unknown as {sent:string[]}).sent[1])!=='Follow up')throw new Error('Instructions repeated');
  await firstChat.evaluate(()=>{history.pushState({},'', '/a/chat/s/first');window.dispatchEvent(new PopStateEvent('popstate'));});
  await firstChat.evaluate(()=>{history.pushState({},'', '/');window.dispatchEvent(new PopStateEvent('popstate'));});
  await firstChat.locator('textarea').fill('New conversation');await firstChat.locator('[role="button"]').click();
  await firstChat.waitForFunction(()=> 'sent' in window && Array.isArray(window.sent) && window.sent.length===3);
  if(!await firstChat.evaluate(()=> (window as unknown as {sent:string[]}).sent[2].endsWith('User request:\nNew conversation')))throw new Error('New conversation click missed instructions');
  await firstChat.close();
  const chat=await context.newPage();await chat.goto('https://chat.deepseek.com/');
  await chat.evaluate(()=>history.pushState({},'', '/a/chat/s/fixture'));
  await chat.locator('textarea').fill('Existing conversation request');await chat.locator('[role="button"]').click();
  if(await chat.evaluate(()=> (window as unknown as {sent:string[]}).sent[0])!=='Existing conversation request')throw new Error('Existing chat was modified');
  await chat.evaluate(()=>{(window as unknown as {sent:string[]}).sent=[];});
  await panel.locator('#preset').selectOption('ask');
  await chat.evaluate(()=>{const block=document.createElement('div');block.className='ds-assistant-message-main-content';block.innerHTML='<div class="md-code-block"><div class="md-code-block-banner"><span>mcp</span></div><pre></pre></div>';block.querySelector('pre')!.textContent=JSON.stringify({id:'card-approval',server:'http',tool:'echo',arguments:{value:'approved-on-card'}});document.querySelector('#messages')!.append(block);});
  const approvalCard=chat.locator('.mcp-card').filter({hasText:'card-approval'});await approvalCard.locator('.mcp-card-header').click();
  const approve=approvalCard.getByRole('button',{name:'Approve',exact:true});await approve.waitFor();
  await approve.evaluate(button=>(button as HTMLButtonElement).click());
  if(await chat.evaluate(()=> (window as unknown as {sent:string[]}).sent.length)!==0)throw new Error('Synthetic click approved command');
  await approve.click();await chat.waitForFunction(()=> (window as unknown as {sent:string[]}).sent.some(text=>text.includes('approved-on-card')));
  await approve.waitFor({state:'detached'});
  await chat.evaluate(()=>{(window as unknown as {sent:string[]}).sent=[];});
  await panel.locator('#preset').selectOption('yolo');
  await panel.click('#tab-tools');
  const yoloTool=panel.locator('.tool-card').filter({has:panel.locator('.tag').getByText('http',{exact:true})});
  await yoloTool.locator('summary').first().click();await yoloTool.getByLabel('Consequential',{exact:true}).check();await yoloTool.getByLabel('Sensitive output',{exact:true}).check();await yoloTool.getByRole('button',{name:'Save review'}).click();
  await chat.evaluate(()=>{const message=document.createElement('div');message.id='streamed-batch';message.className='ds-assistant-message-main-content';document.querySelector('#messages')!.append(message);const stop=document.createElement('button');stop.setAttribute('aria-label','Stop generating');document.body.append(stop);});
  for(const server of ['http','sse','ws']){
   await chat.evaluate(server=>{const block=document.createElement('div');block.className='md-code-block';block.innerHTML='<div class="md-code-block-banner"><span>mcp</span></div><pre></pre>';block.querySelector('pre')!.textContent=JSON.stringify({id:server,server,tool:'echo',arguments:{value:'page-'+server}});document.querySelector('#streamed-batch')!.append(block);},server);
   await chat.waitForTimeout(1000);
   if(await chat.evaluate(()=> (window as unknown as {sent:string[]}).sent.length))throw new Error('Partial streamed batch submitted');
  }
  await chat.evaluate(()=>document.querySelector('[aria-label="Stop generating"]')!.remove());
  await chat.waitForFunction(()=> (window as unknown as {sent:string[]}).sent.some(text=>text.includes('page-ws')));
  const sent=await chat.evaluate(()=> (window as unknown as {sent:string[]}).sent);
  const results=[...sent[0].matchAll(/```mcp-result\n([\s\S]*?)\n```/g)].map(match=>JSON.parse(match[1]));
  if(sent.length!==1||JSON.stringify(results.map(result=>result.id))!==JSON.stringify(['http','sse','ws']))throw new Error('Incorrect batched correlated submissions');
  await chat.evaluate(()=>{const block=document.querySelector('.ds-assistant-message-main-content')!;document.querySelector('#messages')!.append(block.cloneNode(true));});
  await chat.waitForTimeout(100);if(await chat.evaluate(()=> (window as unknown as {sent:string[]}).sent.length)!==1)throw new Error('Replay submitted twice');
  console.log('Browser proof: sidebar HTTP/SSE/WS, reattachment, 3 correlated DeepSeek results, replay suppressed');
  await panel.click('#tab-settings');
  await panel.locator('#preset').selectOption('server-perms');
  await chat.evaluate(()=>{const message=document.createElement('div');message.className='ds-assistant-message-main-content';message.innerHTML='<div class="md-code-block"><div class="md-code-block-banner"><span>mcp</span></div><pre></pre></div>';message.querySelector('pre')!.textContent=JSON.stringify({id:'workspace-prompt',server:'ws',tool:'echo',arguments:{value:'workspace-approval'}});document.querySelector('#messages')!.append(message);});
  const workspaceCard=chat.locator('.mcp-card').filter({has:chat.locator('.mcp-card-identity small').getByText('workspace-prompt',{exact:true})});
  await workspaceCard.getByRole('button',{name:'Approve',exact:true}).waitFor();
  if(await workspaceCard.locator('input').count())throw new Error('Fixed canonical approval still asks for input');
  await panel.locator('#pending-count').getByText('1',{exact:true}).waitFor();
  await panel.click('#tab-activity');
  await panel.locator('#prompts').getByRole('button',{name:'Approve',exact:true}).waitFor();
  await workspaceCard.getByRole('button',{name:'Approve',exact:true}).click();
  await chat.waitForFunction(()=> (window as unknown as {sent:string[]}).sent.some(text=>text.includes('workspace-prompt')&&text.includes('approved_path')));
  const workspaceResult=await chat.evaluate(()=>(window as unknown as {sent:string[]}).sent.find(text=>text.includes('workspace-prompt'))!);
  const workspacePayload=JSON.parse(workspaceResult.match(/```mcp-result\n([\s\S]*?)\n```/)![1]);
  const workspaceReply=JSON.parse(workspacePayload.result.structuredContent.value);
  if(workspaceReply.action!=='accept'||workspaceReply.content.approved_path!=='S:\\Data\\CODE\\Rust')throw new Error('Canonical path approval changed');
  await panel.click('#tab-settings');
  await panel.locator('#preset').selectOption('yolo');
  await chat.evaluate(()=>{const message=document.createElement('div');message.className='ds-assistant-message-main-content';message.innerHTML='<div class="md-code-block"><div class="md-code-block-banner"><span>mcp</span></div><pre></pre></div>';message.querySelector('pre')!.textContent=JSON.stringify({id:'workspace-auto',server:'ws',tool:'echo',arguments:{value:'workspace-approval'}});document.querySelector('#messages')!.append(message);});
  await chat.waitForFunction(()=> (window as unknown as {sent:string[]}).sent.some(text=>text.includes('workspace-auto')&&text.includes('approved_path')));
  const auto=await chat.evaluate(()=>(window as unknown as {sent:string[]}).sent.find(text=>text.includes('workspace-auto'))!);
  const autoReply=JSON.parse(JSON.parse(auto.match(/```mcp-result\n([\s\S]*?)\n```/)![1]).result.structuredContent.value);
  if(autoReply.action!=='accept'||autoReply.content.approved_path!=='S:\\Data\\CODE\\Rust')throw new Error('YOLO elicitation approval failed');
  await chat.evaluate(()=>{const message=document.createElement('div');message.className='ds-assistant-message-main-content';const status=document.createElement('div');status.className='md-code-block';status.innerHTML='<div class="md-code-block-banner"><span>mcp-status</span></div><pre>{"id":"status-mixed"}</pre>';message.append(status);for(const [id,tool] of [['batch-ok','echo'],['batch-fail','missing']]){const block=document.createElement('div');block.className='md-code-block';block.innerHTML='<div class="md-code-block-banner"><span>mcp</span></div><pre></pre>';block.querySelector('pre')!.textContent=JSON.stringify({id,server:'http',tool,arguments:{value:'mixed-result'}});message.append(block);}document.querySelector('#messages')!.append(message);});
  await chat.waitForFunction(()=> (window as unknown as {sent:string[]}).sent.some(text=>text.includes('batch-fail')));
  const mixed=await chat.evaluate(()=> (window as unknown as {sent:string[]}).sent.filter(text=>text.includes('batch-fail')));
  const mixedResults=[...mixed[0].matchAll(/```mcp-result\n([\s\S]*?)\n```/g)].map(match=>JSON.parse(match[1]));
  if(mixed.length!==1||mixedResults[0].id!=='batch-ok'||!mixedResults[0].result||mixedResults[1].id!=='batch-fail'||!mixedResults[1].error)throw new Error('Mixed batch lost success or error');
  const statusMatch=mixed[0].match(/```mcp-status-result\n([\s\S]*?)\n```/);
  if(!statusMatch)throw new Error('Status missing from mixed batch');
  const status=JSON.parse(statusMatch[1]);
  if(status.id!=='status-mixed'||JSON.stringify(status.result.servers.map((server:{name:string})=>server.name))!==JSON.stringify(['http','sse','ws'])||JSON.stringify(status).includes('127.0.0.1'))throw new Error('Incorrect or private server status');
  const statusCard=chat.locator('.mcp-card').filter({has:chat.locator('.mcp-card-identity small').getByText('status-mixed',{exact:true})});await statusCard.locator('.mcp-card-header').click();await statusCard.getByRole('heading',{name:'Response',exact:true}).waitFor();await statusCard.scrollIntoViewIfNeeded();await chat.screenshot({path:'.output/status-block-proof.png'});
  await chat.locator('textarea').fill('user draft');
  await chat.evaluate(()=>{const block=document.querySelector('.ds-assistant-message-main-content')!.cloneNode(true) as HTMLElement;block.querySelector('pre')!.textContent=JSON.stringify({id:'occupied',server:'http',tool:'echo',arguments:{value:'retained-result'}});block.querySelectorAll('.mcp-card').forEach(e=>e.remove());document.querySelector('#messages')!.append(block);});
  await chat.locator('[data-mcp-runner-id]').last().locator('.mcp-card-status').getByText('Result ready',{exact:true}).waitFor();
  if(await chat.locator('textarea').inputValue()!=='user draft')throw new Error('Composer draft overwritten');
  await chat.locator('textarea').fill('');
  await chat.waitForFunction(()=> 'sent' in window && Array.isArray(window.sent) && window.sent.some(text=>typeof text==='string' && text.includes('retained-result')));
  await chat.evaluate(()=>{const message=document.createElement('div');message.className='ds-message';const text=document.createElement('div');text.textContent='```mcp-result\n'+JSON.stringify({id:'http',server:'http',tool:'echo',result:{content:[{type:'text',text:JSON.stringify({value:'user-result',nested:{items:[0,false,null,'',{},[]]}})},{type:'text',text:'{malformed <img src=x onerror=alert(1)>'}],structuredContent:{path:'.gitignore',lines:[{number:1,text:'node_modules/'}]},isError:false}})+'\n```';message.append(text);document.querySelector('#messages')!.append(message);});
  const userCard=chat.locator('[data-mcp-user-block]');await userCard.waitFor();
  if(await userCard.evaluate(e=>(e as HTMLDetailsElement).open))throw new Error('Card should begin collapsed');
  await userCard.locator('.mcp-card-header').focus();await chat.keyboard.press('Enter');
  await userCard.locator('.mcp-payload-surface').getByText('user-result',{exact:true}).waitFor();
  const surface=userCard.locator('.mcp-payload-surface');
  await surface.getByText('user-result',{exact:true}).waitFor();
  await surface.getByText('Array · 6 items',{exact:true}).click();
  await surface.getByText('0',{exact:true}).waitFor();await surface.getByText('null',{exact:true}).waitFor();await surface.getByText('"" · empty string',{exact:true}).waitFor();
  if(await surface.locator('img').count())throw new Error('Response text became HTML');
  await surface.getByText('{malformed <img src=x onerror=alert(1)>',{exact:true}).waitFor();
  await userCard.locator('.mcp-raw-json summary').click();
  const raw=JSON.parse(await userCard.locator('.mcp-raw-json pre').innerText());
  if(raw.content[0].text!==JSON.stringify({value:'user-result',nested:{items:[0,false,null,'',{},[]]}}))throw new Error('Raw payload changed');
  await userCard.locator('.mcp-raw-json summary').click();await userCard.scrollIntoViewIfNeeded();await chat.screenshot({path:'.output/structured-block-proof.png'});
  await panel.emulateMedia({colorScheme:'light'});
  console.log('Dark-mode computed styles',await panel.evaluate(()=>({scheme:getComputedStyle(document.documentElement).colorScheme,background:getComputedStyle(document.documentElement).backgroundColor})));
  await panel.evaluate(()=>window.scrollTo(0,0));
  await panel.click('#tab-servers');
  await panel.screenshot({path:'.output/sidebar-proof.png'});await chat.screenshot({path:'.output/deepseek-proof.png'});
  const httpProfile=panel.locator('.profile-card').filter({has:panel.locator('strong').getByText('http',{exact:true})});
  if(!await httpProfile.getByRole('button',{name:'Edit',exact:true}).isDisabled())throw new Error('Connected profile is editable');
  await httpProfile.getByRole('button',{name:'Disconnect',exact:true}).click();await httpProfile.getByText('disconnected',{exact:true}).waitFor();
  await httpProfile.getByRole('button',{name:'Edit',exact:true}).click();
  if(await panel.locator('[name="url"]').inputValue()!==fixture.url+'/mcp')throw new Error('Edit did not prefill endpoint');
  await panel.locator('[name="name"]').fill('sse');await panel.getByRole('button',{name:'Save profile',exact:true}).click();await panel.getByRole('alert').getByText('Profile name already exists',{exact:true}).waitFor();
  await panel.locator('#cancel-profile').click();await httpProfile.getByRole('button',{name:'Edit',exact:true}).click();
  if(await panel.locator('[name="name"]').inputValue()!=='http')throw new Error('Cancel changed profile');
  await panel.locator('[name="name"]').fill('renamed');await panel.locator('[name="url"]').fill(fixture.url+'/sse');await panel.locator('[name="transport"]').selectOption('sse');
  await panel.getByRole('button',{name:'Save profile',exact:true}).click();await panel.locator('#profile-form').waitFor({state:'hidden'});
  const renamed=panel.locator('.profile-card').filter({has:panel.locator('strong').getByText('renamed',{exact:true})});await renamed.getByRole('button',{name:'Connect',exact:true}).click();await renamed.getByText('connected',{exact:true}).waitFor();
  await panel.click('#tab-tools');
  const renamedTool=panel.locator('.tool-card').filter({has:panel.locator('.tag').getByText('renamed',{exact:true})});await renamedTool.locator('summary').first().click();
  if(await renamedTool.getByLabel('Read-only',{exact:true}).isChecked())throw new Error('Endpoint change retained old review');
  await panel.click('#tab-servers');
  await renamed.scrollIntoViewIfNeeded();await panel.screenshot({path:'.output/profile-edit-proof.png'});
  for(const action of ['disconnect','connect'] as const){
   const id='status-'+action;
   await chat.evaluate(({id,action})=>{const message=document.createElement('div');message.className='ds-assistant-message-main-content';message.innerHTML='<div class="md-code-block"><div class="md-code-block-banner"><span>mcp-status</span></div><pre></pre></div>';message.querySelector('pre')!.textContent=JSON.stringify({id,action,server:'renamed'});document.querySelector('#messages')!.append(message);},{id,action});
   await chat.waitForFunction(id=>(window as unknown as {sent:string[]}).sent.some(text=>text.includes(id)),id);
   const text=await chat.evaluate(id=>(window as unknown as {sent:string[]}).sent.find(text=>text.includes(id))!,id);
   const payload=JSON.parse(text.match(/```mcp-status-result\n([\s\S]*?)\n```/)![1]);
   if(payload.result.servers.find((server:{name:string})=>server.name==='renamed').status!==(action==='connect'?'connected':'disconnected'))throw new Error('Status action did not change connection');
  }
 }catch(error){for(const page of context.pages())console.log('Failure surface',page.url(),await page.locator('body').innerText());throw error;}finally{await context.close();await fixture.close();}
}});
